print("welcome to the world using jenkins")
print("qwerty is the machince")
print("all oceans are blue and all fishes are white")
print("all the people who are in the team was working in the situation to the person of the world")
print("great man reached their heights when there companions are sleeping at nights")
print("The time is always right to do what is right")
print("We are the peole firstly and lastly")
